/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TP2;

import java.io.IOException;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        try {
            new Game().run();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
